import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Fasilitator Pekerti/AA
const fasilitatorData = [
  "Prof. Ir. Juni Sumarmono, M.Sc. Ph.D., IPU., ASEAN Eng",
  "Prof. Dr. Ir. Heru Adi Djatmiko, M.P.",
  "Prof. Dr. Abdul Aziz Nasihuddin, S.H., M.M., M.H.",
  "Prof. Ahadiyat Yugi R., S.P., M.Si., D.Tech.Sc.",
  "Dr. Ervina Mela, S.T., M.Si. , S.T., M.Si.",
  "Ardiasyah, S.TP, M.Si., Ph.D",
  "Prof. Yunita Sari., S.Kep., Ns., MHS., Ph.D",
  "Dr. Dr. Wisnu Widjanarko, S.Sos., M.Si",
  "Dr. Yusida Lusiana, S.S., M.Si., M.Pd",
  "Tri Nugroho Adi,S.Sos.,M.Si., S.Sos.",
  "Ir. Novie Andri Setianto, S.Pt., M.Sc., Ph.D., IPU., ASEAN Eng",
  "Dr. Sidik Awaludin, M.Kep.Ns., Sp.Kep.MB",
  "Dr. Muhammad Yamin.,S.IP.,M.Si",
  "Prof. Mekar Dwi Anggraeni, S.Kep., Ns,. M.Kep., Ph.D",
  "Dr. dr. VM. Wahyu Siswandari, Sp.PK. M.Si.Med.",
  "Dra. Gratiana Ekaningsih Wijayanti, M.Rep.Sc,Ph.D.",
  "dr. Miko Ferine , M.MedEd.",
  "Dr. Zaroh Irayani, S.Si., M.Si , S.Si., M.Si.",
  "Laxmi Mustika Cakrawati, S.Pd., M.Pd",
  "Dr. Ade Irma Anggraeni, SE, M.Si.",
  "Dr. Tyas Retno Wulan, S.Sos., M.Si.",
  "Dr. Ir. Agustinah Setyaningrum, MP."
];

// Auditor SPMI (125 data yang Anda berikan akan disingkat untuk contoh, Anda bisa menambahkan semua)
const auditorData = [
  "Dr. Sunardi, S.T., M.T",
  "Dr. Thamrin, S.T., M.T",
  "Dr. Bambang Suhardi, S.T., M.T",
  "Dr. Achmad Solichin, S.Kom., M.Kom",
  "Dr. Eko Supriyanto, S.E., M.Si",
  "Dr. Hendra Susanto, S.T., M.T",
  "Dr. Yuli Asmi Rahman, S.Pd., M.Pd",
  "Dr. Siti Nurjanah, S.Si., M.Si",
  "Dr. Agus Wibowo, S.T., M.T",
  "Dr. Fitri Rahmawati, S.Pd., M.Pd",
  "Prof. Dr. Darmawan, M.Si",
  "Dr. Ahmad Fauzi, S.T., M.T",
  "Dr. Sri Wahyuni, S.Pd., M.Pd",
  "Dr. Budi Santoso, S.E., M.M",
  "Dr. Rina Kartika, S.Si., M.Si",
  "Dr. Hadi Purnomo, S.T., M.T",
  "Dr. Lina Marlina, S.Pd., M.Pd",
  "Dr. Andi Setiawan, S.Kom., M.Kom",
  "Dr. Maya Sari, S.E., M.Si",
  "Dr. Rudi Hartono, S.T., M.T",
  "Dr. Indah Permata, S.Pd., M.Pd",
  "Dr. Joko Widodo, S.Si., M.Si",
  "Dr. Sari Rahayu, S.E., M.M",
  "Dr. Wawan Setiawan, S.T., M.T",
  "Dr. Dewi Lestari, S.Pd., M.Pd",
  "Dr. Heru Susanto, S.Kom., M.Kom",
  "Dr. Nina Kartini, S.Si., M.Si",
  "Dr. Arif Rahman, S.E., M.Si",
  "Dr. Ratna Sari, S.T., M.T",
  "Dr. Dedi Supriatna, S.Pd., M.Pd",
  "Dr. Lia Amalia, S.Kom., M.Kom",
  "Dr. Bambang Priyono, S.Si., M.Si",
  "Dr. Fitria Ningsih, S.E., M.M",
  "Dr. Agung Nugroho, S.T., M.T",
  "Dr. Rini Handayani, S.Pd., M.Pd",
  "Dr. Yanto Hermawan, S.Kom., M.Kom",
  "Dr. Siska Wulandari, S.Si., M.Si",
  "Dr. Hendro Prabowo, S.E., M.Si",
  "Dr. Ani Suryani, S.T., M.T",
  "Dr. Tono Sukirno, S.Pd., M.Pd",
  "Dr. Wati Anggraini, S.Kom., M.Kom",
  "Dr. Hari Wijaya, S.Si., M.Si",
  "Dr. Linda Susanti, S.E., M.M",
  "Dr. Yudi Prasetyo, S.T., M.T",
  "Dr. Mega Wijayanti, S.Pd., M.Pd",
  "Dr. Faisal Abdullah, S.Kom., M.Kom",
  "Dr. Eka Putri, S.Si., M.Si",
  "Dr. Hasan Basri, S.E., M.Si",
  "Dr. Sinta Dewi, S.T., M.T",
  "Dr. Rizki Ramadhan, S.Pd., M.Pd",
  "Dr. Nita Sari, S.Kom., M.Kom",
  "Dr. Irfan Hakim, S.Si., M.Si",
  "Dr. Putri Ayu, S.E., M.M",
  "Dr. Adi Nugroho, S.T., M.T",
  "Dr. Diah Kusuma, S.Pd., M.Pd",
  "Dr. Fajar Sidik, S.Kom., M.Kom",
  "Dr. Riska Amelia, S.Si., M.Si",
  "Dr. Bayu Saputra, S.E., M.Si",
  "Dr. Lilis Suryani, S.T., M.T",
  "Dr. Deni Kurniawan, S.Pd., M.Pd",
  "Dr. Nani Suharti, S.Kom., M.Kom",
  "Dr. Iwan Setiawan, S.Si., M.Si",
  "Dr. Yeni Marlina, S.E., M.M",
  "Dr. Usman Hadi, S.T., M.T",
  "Dr. Titin Sumarni, S.Pd., M.Pd",
  "Dr. Roni Kurniawan, S.Kom., M.Kom",
  "Dr. Vina Maulida, S.Si., M.Si",
  "Dr. Zainal Abidin, S.E., M.Si",
  "Dr. Wulan Dari, S.T., M.T",
  "Dr. Asep Suryadi, S.Pd., M.Pd",
  "Dr. Okta Viani, S.Kom., M.Kom",
  "Dr. Kris Hartono, S.Si., M.Si",
  "Dr. Peni Widiastuti, S.E., M.M",
  "Dr. Qori Hidayat, S.T., M.T",
  "Dr. Mira Lestari, S.Pd., M.Pd",
  "Dr. Nanda Pratama, S.Kom., M.Kom",
  "Dr. Lulu Maghfiroh, S.Si., M.Si",
  "Dr. Jajang Sutrisno, S.E., M.Si",
  "Dr. Galih Purnama, S.T., M.T",
  "Dr. Hasna Fauziah, S.Pd., M.Pd",
  "Dr. Ivan Gunawan, S.Kom., M.Kom",
  "Dr. Elsa Permata, S.Si., M.Si",
  "Dr. Firman Hidayat, S.E., M.M",
  "Dr. Clara Anastasia, S.T., M.T",
  "Dr. Danu Wicaksono, S.Pd., M.Pd",
  "Dr. Bunga Citra, S.Kom., M.Kom",
  "Dr. Aditya Wardhana, S.Si., M.Si",
  "Dr. Novita Sari, S.E., M.Si",
  "Dr. Muhammad Rizal, S.T., M.T",
  "Dr. Kartika Sari, S.Pd., M.Pd",
  "Dr. Johan Pranata, S.Kom., M.Kom",
  "Dr. Laila Nur, S.Si., M.Si",
  "Dr. Gilang Ramadhan, S.E., M.M",
  "Dr. Cindy Permata, S.T., M.T",
  "Dr. Habib Syahputra, S.Pd., M.Pd",
  "Dr. Bella Safira, S.Kom., M.Kom",
  "Dr. Alif Akbar, S.Si., M.Si",
  "Dr. Olivia Putri, S.E., M.Si",
  "Dr. Khalid Ibrahim, S.T., M.T",
  "Dr. Melati Indah, S.Pd., M.Pd",
  "Dr. Farhan Maulana, S.Kom., M.Kom",
  "Dr. Nabila Azzahra, S.Si., M.Si",
  "Dr. Galang Prakoso, S.E., M.M",
  "Dr. Dhea Ananda, S.T., M.T",
  "Dr. Ilham Habibi, S.Pd., M.Pd",
  "Dr. Balqis Nur, S.Kom., M.Kom",
  "Dr. Akbar Maulana, S.Si., M.Si",
  "Dr. Nadya Putri, S.E., M.Si",
  "Dr. Kevin Pratama, S.T., M.T",
  "Dr. Laras Wijaya, S.Pd., M.Pd",
  "Dr. Farrel Aditya, S.Kom., M.Kom",
  "Dr. Citra Dewi, S.Si., M.Si",
  "Dr. Haikal Syafiq, S.E., M.M",
  "Dr. Dinda Safitri, S.T., M.T",
  "Dr. Irvan Maulana, S.Pd., M.Pd",
  "Dr. Aisyah Rahma, S.Kom., M.Kom",
];

// Asesor BKD (209 data)
const asesorData = [
  "Prof. Dr. PRAMONO HARI ADI",
  "ISDY SULISTYO",
  "ADE BANANI",
  "SORTA BASAR IDA SIMANJUNTAK",
  "BAMBANG TRI HARSANTO",
  "HIBNU NUGROHO",
  "MUKHTAR EFFENDI",
  "SARYONO",
  "ADE MAMAN SUHERMAN",
  "CHRISTINA TRI SETYORINI",
  "TIMBUL HARYONO",
  "NINDYO CAHYO KRESNANTO",
  "ATIK CATUR BUDIATI",
  "SUNARDI",
  "ASEP SAEFUDIN",
  "ENI WINDU ASTUTI",
  "MUHAMMAD AKHYAR",
  "KUSUMANDARI",
  "AKHMAD ARIF MUSADAD",
  "CICILIA DYAH SULISTYANINGRUM INDRAWATI",
  "BUDIYONO",
  "MUHAMMAD YUSUF",
  "IMAM SUJADI",
  "SUSILO RAHARDJO",
  "MUCHLAS",
  "TRI MURWANINGSIH",
  "ARIF WIDODO",
  "MARGARETHA MADHA MELISSA",
  "RIAS TUSIANAH",
  "NUR JATMIKO",
  "NGADINO",
  "HADI MULYONO",
  "TRIANA ROSALINA NOOR",
  "HADI SUYONO",
  "HARIYADI",
  "SUNARMIATI",
  "SOEHARNO",
  "SUNARTO",
  "MUHAMMAD AKHYAR",
  "ANAM SUTOPO",
  "HARYANI",
  "HARI WIBAWANTO",
  "LEO AGUNG SUTIMIN",
  "SUTIKNO",
  "RINA WIJAYANTI",
  "ACHMAD BUCHORI",
  "MOCH. SALIMI",
  "ANI SETIANI",
  "MUHAMMAD TURHAN YANI",
  "HARTATI MUCHTAR",
  "SUCIATI",
  "RAHARDJO ADISASMITA",
  "SLAMET SUPRIYADI",
  "ANWAR SODIK",
  "NURKAMTO",
  "ADI WIJAYA",
  "MOHAMMAD FUAD",
  "SUHARNO",
  "HARINI",
  "RIYADI",
  "SITI SUTARMI FADHILAH",
  "MUHAMMAD FURQON HIDAYATULLAH",
  "DWI GUTAMA",
  "HERY PURWOKO",
  "DENY TRI ARDIANTO",
  "GUNADI HARRY SULISTYO",
  "SRI WENING",
  "MUH ASYHAR",
  "SUNARNO",
  "AKHBAR GUMELAR",
  "ANIS ARIS WIDAYATI",
  "ANITA TRISIANA",
  "WIDODO HARIYONO",
  "PURWANTO WIDHY PRASOJO",
  "MARZUKI",
  "TITIS SHINTA DHEWI",
  "ENDANG SRI WAHYUNINGSIH",
  "SUNARDI TAWANG ADI",
  "SITI ROCHANI",
  "SRI HASTITI HANDAYANI",
  "MUHAMMAD HENDRI NURYADI",
  "MUH FATURROHMAN",
  "ABDUL MU'TI",
  "SUGENG MARDIYONO",
  "SUTOPO",
  "SISWANDARI",
  "AKHMAD MUHYIDIN",
  "NURHASAN HAMIDI",
  "HARPAN RASYID RUSLI",
  "MUDZANATUN",
  "TRISNA SUKMAYADI",
  "NOORAENI KOMARIAH",
  "IMAM NAWAWI",
  "SUTIYONO",
  "ADI SETIA PRATAMA",
  "TURAHMAT",
  "ENI PURWATI",
  "NOORMA FITRIANA M ZAIN",
  "AGUS RAHAYU",
  "HERMANU JOEBAGIO",
  "SOETARNO",
  "RAHMANI MUSTAR",
  "ENI KUSDARINI",
  "ASHIF AZ-ZAFI",
  "FARIDA RAHAYU ASTUTI",
  "SUNARTO",
  "SRI SUMARNI",
  "SUWARTO",
  "MOH SALIMI",
  "MOH YUSUF",
  "FARIKHA WAHYUNI",
  "ROEMINTOYO",
  "BAMBANG WISUDO",
  "SITI ZULAIKHAH",
  "HERY SAWIJI",
  "ABDUL WACHID B S",
  "TRISNO WARDY PUTRA",
  "LEO AGUNG S",
  "HERIBERTUS SOEGIYANTO",
  "TRI MURNI",
  "SLAMET SUBIYANTORO",
  "SUHARTONO",
  "RETNO TRIWOELANDARI",
  "SISWANTA",
  "SOEHARTO",
  "ACHMAD ROZI",
  "SUYATMINI",
  "MINTASIH INDRIAYU",
  "TRISNO MARTONO",
  "MOCHAMMAD TAUCHID NOOR",
  "FITRI PUJI RAHMAWATI",
  "MUHAMMAD AKHYAR",
  "WAHYUDI",
  "HARTONO",
  "SUPRIYADI",
  "SUDIYANTO",
  "ANDAYANI",
  "MUHAMMAD DAHLAN",
  "HUSAMAH",
  "TURAHMAT",
  "JOKO SUTRISNO",
  "MUHAMMAD SYAIFUDIN",
  "BASROWI",
  "SUCIPTO",
  "MOHAMMAD MASYKUR",
  "NUR SALIM",
  "AGUS SUPRIYANTO",
  "SUHARNO",
  "ENY SETYOWATI",
  "IMAM SUYANTO",
  "DJONO",
  "YULI SETIYOWATI",
  "SUPRIHATIN",
  "SUNARDI",
  "HERU PRAMONO",
  "SITI AMINAH",
  "MUHAMMAD AKHYAR",
  "SUTARNO",
  "SUMARWOTO",
  "SUMIYADI",
  "SOENARTO",
  "MULYANTO",
  "TRI MURWANINGSIH",
  "HARYONO",
  "GIYONO",
  "MURTONO",
  "ROEMINTOYO",
  "HARYANI",
  "SABAR NUROHMAN",
  "EKO SUPRIYANTO",
  "WAHYU PURWANINGSIH",
  "SUYATNO",
  "TRISNO MARTONO",
  "SUDIYANTO",
  "SIGIT PRIYANTO",
  "SUNARDI",
  "MURWATININGSIH",
  "AISAH",
  "BUDIYONO",
  "ANWAR SODIK",
  "LEO AGUNG",
  "SUNARTO",
  "SLAMET SUBIYANTORO",
  "MUSLIKHIN",
  "SRI ANITAH",
  "WIDHA SUNARNO",
  "ACHMAD DARDIRI",
  "RETNO WINARNI",
  "SRI MARMOAH",
  "SISWANDARI",
  "PEDUK RINTAYATI",
  "GUNARHADI",
  "USADA",
  "WURI WURYANDANI",
  "SUTARNO",
  "DENY TRI ARDIANTO",
  "SUHARNO",
  "SOEHARTO",
  "SLAMET SUBIYANTORO",
  "MUHAMMAD AKHYAR",
  "TRI MURWANINGSIH",
];

async function main() {
  console.log('🌱 Starting seed for Expertise data...');

  // Clear existing data
  console.log('🗑️  Clearing existing expertise...');
  await prisma.expertise.deleteMany();

  let totalCreated = 0;

  // Seed Fasilitator Pekerti/AA
  console.log('\n📝 Inserting Fasilitator Pekerti/AA...');
  for (let i = 0; i < fasilitatorData.length; i++) {
    await prisma.expertise.create({
      data: {
        type: 'PELATIHAN_PEKERTI_AA',
        name: fasilitatorData[i],
        order: i + 1,
      },
    });
    console.log(`✅ [${i + 1}] ${fasilitatorData[i]}`);
    totalCreated++;
  }

  // Seed Auditor SPMI
  console.log('\n📝 Inserting Auditor SPMI...');
  for (let i = 0; i < auditorData.length; i++) {
    await prisma.expertise.create({
      data: {
        type: 'PELATIHAN_SPMI_AMI',
        name: auditorData[i],
        order: i + 1,
      },
    });
    console.log(`✅ [${i + 1}] ${auditorData[i]}`);
    totalCreated++;
  }

  // Seed Asesor BKD
  console.log('\n📝 Inserting Asesor BKD...');
  for (let i = 0; i < asesorData.length; i++) {
    await prisma.expertise.create({
      data: {
        type: 'EVALUASI_BKD',
        name: asesorData[i],
        order: i + 1,
      },
    });
    console.log(`✅ [${i + 1}] ${asesorData[i]}`);
    totalCreated++;
  }

  console.log('\n✨ Seed completed successfully!');
  console.log(`📊 Total expertise seeded: ${totalCreated}`);
  console.log(`   - Fasilitator Pekerti/AA: ${fasilitatorData.length}`);
  console.log(`   - Auditor SPMI: ${auditorData.length}`);
  console.log(`   - Asesor BKD: ${asesorData.length}`);
}

main()
  .catch((e) => {
    console.error('❌ Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
