/* eslint-disable */
export default {
  "key": "common",
  "content": {
    "nodeType": "translation",
    "translation": {
      "id": {
        "welcomeTo": "Selamat Datang di",
        "subtitle": "Lembaga Penjaminan Mutu dan Pengembangan Pembelajaran",
        "motto": "Unggul dalam Mutu, Inovatif dalam Pembelajaran",
        "readMore": "Baca Selengkapnya",
        "viewAll": "Lihat Semua",
        "loadMore": "Muat Lebih Banyak",
        "search": "Cari",
        "filter": "Filter",
        "download": "Unduh",
        "back": "Kembali",
        "save": "Simpan",
        "cancel": "Batal",
        "send": "Kirim",
        "loading": "Memuat...",
        "noData": "Belum ada data",
        "by": "Oleh",
        "views": "views",
        "downloads": "unduhan",
        "navigation": "Navigasi",
        "services": "Layanan",
        "contactUs": "Hubungi Kami",
        "followUs": "Ikuti Kami",
        "institution": "Lembaga Pengembangan Pembelajaran dan Penjaminan Mutu"
      },
      "en": {
        "welcomeTo": "Welcome to",
        "subtitle": "Quality Assurance and Learning Development Institution",
        "motto": "Excellence in Quality, Innovation in Learning",
        "readMore": "Read More",
        "viewAll": "View All",
        "loadMore": "Load More",
        "search": "Search",
        "filter": "Filter",
        "download": "Download",
        "back": "Back",
        "save": "Save",
        "cancel": "Cancel",
        "send": "Send",
        "loading": "Loading...",
        "noData": "No data yet",
        "by": "By",
        "views": "views",
        "downloads": "downloads",
        "navigation": "Navigation",
        "services": "Services",
        "contactUs": "Contact Us",
        "followUs": "Follow Us",
        "institution": "Learning Development and Quality Assurance Institution"
      },
      "zh": {
        "welcomeTo": "欢迎来到",
        "subtitle": "质量保证与学习发展机构",
        "motto": "卓越品质，创新学习",
        "readMore": "阅读更多",
        "viewAll": "查看全部",
        "loadMore": "加载更多",
        "search": "搜索",
        "filter": "筛选",
        "download": "下载",
        "back": "返回",
        "save": "保存",
        "cancel": "取消",
        "send": "发送",
        "loading": "加载中...",
        "noData": "暂无数据",
        "by": "作者",
        "views": "浏览",
        "downloads": "下载",
        "navigation": "导航",
        "services": "服务",
        "contactUs": "联系我们",
        "followUs": "关注我们",
        "institution": "学习发展与质量保证机构"
      }
    }
  },
  "localIds": [
    "common::local::content/common.content.ts"
  ]
} as const;
